---
    name: test install win 3.13
    
    on:
        push:
            branches:
            -   main
        pull_request:
            branches:
            -   '*'
    
    # Force to use color
    env:
        FORCE_COLOR: true
    
    jobs:
        test_and_coverage:
            name: 'Test with ${{ matrix.py }} on ${{ matrix.os }}'
            runs-on: ${{ matrix.os }}
            strategy:
                fail-fast: false
                matrix:
                    py: ['3.13']
                    os: [windows-latest]
            steps:
                -   uses: actions/checkout@v4
                -   name: Setup python
                    uses: actions/setup-python@v5
                    with:
                        python-version: ${{ matrix.py }}
                        allow-prereleases: true
                -   run: pip install scikit-learn>=1.0.0
